export const options = [
    { value: "sale_agreement", label: "Sale Agreement" },
    { value: "lease_agreement", label: "Lease Agreement" },
    { value: "construction_contract", label: "Construction Contract" },
    { value: "mou", label: "Memorandum of Understanding (MOU)" },
    { value: "joint_venture_agreement", label: "Joint Venture Agreement" },
    { value: "power_of_attorney", label: "Power of Attorney" },
    { value: "development_agreement", label: "Development Agreement" },
    { value: "broker_agreement", label: "Broker Agreement" },
    { value: "sale_deed", label: "Sale Deed" },
    { value: "rent_agreement", label: "Rent Agreement" },
    { value: "license_agreement", label: "License Agreement" },
    { value: "nda", label: "Non-Disclosure Agreement (NDA)" },
    { value: "mortgage_deed", label: "Mortgage Deed" },
    { value: "title_deed", label: "Title Deed" },
    { value: "property_management_agreement", label: "Property Management Agreement" },
    { value: "loan_agreement", label: "Loan Agreement" },
    { value: "mortgage_deed_bank", label: "Mortgage Deed Bank" },
    { value: "deposit_agreement", label: "Deposit Agreement" },
    { value: "credit_agreement", label: "Credit Agreement" },
    { value: "security_agreement", label: "Security Agreement" },
  ];
